name = "feedbackun-web"
main = ".worker-next/index.mjs"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]
assets = { binding = "ASSETS", directory = ".worker-next/assets" }
minify = true
