name: Setup workspace
description: Setup workspace

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: .node-version

    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Expose pnpm store path
      id: pnpm_store_path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm_store_path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Copy .wrangler.toml
      shell: bash
      run: |
        cp ./apps/slack/wrangler.example.toml ./apps/slack/wrangler.toml
        cp ./apps/web/wrangler.example.toml ./apps/web/wrangler.toml
        cp ./packages/database/wrangler.example.toml ./packages/database/wrangler.toml
